replicaCount: 1

image:
  repository: thanhnamdev308/knote-js
  pullPolicy: Always
  tag: "lastest"

service:
  type: NodePort
  port: 81
  targetPort: 3001
  nodePort: 30180

mongoUrl: mongodb://54.159.79.101:27017/knote

env:
  name: prod
