replicaCount: 1

image:
  repository: thanhnamdev308/knote-js
  pullPolicy: Always
  tag: "prod-lastest"

service:
  type: NodePort
  port: 81
  targetPort: 3000
  nodePort: 30180

mongoUrl: mongodb://54.90.225.255:27018/knote-prod

env:
  name: prod
