replicaCount: 1

image:
  repository: thanhnamdev308/knote-js
  pullPolicy: Always
  tag: "lastest"

service:
  type: NodePort
  port: 90
  targetPort: 4000
  nodePort: 40080

mongoUrl: mongodb://54.159.79.101:27017/knote

env:
  name: prod
