replicaCount: 1

image:
  repository: thanhnamdev308/knote-js
  pullPolicy: Always
  tag: "lastest"

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30080

mongoUrl: mongodb://54.90.225.255:27017/knote-dev

env:
  name: dev
