apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knote-js.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "knote-js.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "knote-js.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: knote-js-configmap
                  key: MONGO_URL

{{- with .Values.env }}
{{- range $key, $value := . }}
- name : {{ $key | quote}}
value : {{ $value | quote}}
{{- end}}
{{- end}}
