apiVersion: v1
kind: Service
metadata:
  name: {{ include "knote-js.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "knote-js.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
